### ISSUE TITLE
C code in rustic

### ISSUE THREAD

**Issue by pmros** [miselin/rustic#8]
Hi,
I wonder if you should use C code in rustic. I mean it would be better if you use only asm (inline or external) and Rust, like rustboot does.
It's just a sugestion from a poor newbie. Good work! Go on!

**Comment by miselin** [comment]
Sorry to revive an ancient issue thread, but (to my knowledge) there is no remaining C code in the repository as of today's set of commits. Some external assembly still exists to bootstrap the runtime environment when handed off from the bootloader.
